Run

diff --git a/.github/workflows/nest-app.yml b/.github/workflows/nest-app.yml
--- a/.github/workflows/nest-app.yml
+++ b/.github/workflows/nest-app.yml
@@ -91,13 +91,14 @@ jobs:
       - name: Run Terraform plan
         working-directory: ./terraform-module-ecs-cicd/nest-app
         run: |
-          terraform plan -no-color 2>&1 | tee plan-output.txt 
-          exit ${PIPESTATUS[0]}
+          terraform plan -no-color 
+      # 2>&1 | tee plan-output.txt 
+      #     exit ${PIPESTATUS[0]}
       
-      - name: Show plan output on failure
-        if: failure()
-        working-directory: ./terraform-module-ecs-cicd/nest-app
-        run: cat plan-output.txt
+      # - name: Show plan output on failure
+      #   if: failure()
+      #   working-directory: ./terraform-module-ecs-cicd/nest-app
+      #   run: cat plan-output.txt
 
       - name: Run Terraform apply/destroy
         working-directory: ./terraform-module-ecs-cicd/nest-app
